version: "3.9"

services:
  train:
    image: train:1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoadmin:secret@mongodb:27017/train?retryWrites=true&w=majority&authSource=admin
    container_name: train-app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - /tmp/mongodata:/data/db
    container_name: mongodb